== Cluster Interaction

The Cluster Interaction feature allows OpenShift Lightspeed to interact and gather information from your OpenShift cluster in a read-only manner. This enables the LLM to generate highly customized responses for your environment.

NOTE: This is currently a Technology Preview feature of OpenShift Lightspeed.

OpenShift Lightspeed includes an MCP server already preconfigured to communicate with the OpenShift API. This server provides some built-in tools, such as _oc_get_, _oc_describe_, _oc_logs_, etc. When the cluster interaction flag is enabled, the model may choose to call one of those tools to retrieve relevant information directly from the cluster to support your query. All tool usage is performed using the user's own credentials and access rights, preventing any privilege escalation.

Cluster Interaction is enabled in our environment, so you can try asking some questions about cluster resources and see how OpenShift Lightspeed responds. For example, you can ask:

[source,role="execute",subs=attributes+]
----
What are the pods in the openshift-lightspeed namespace?
----

The GPT-4 model likely chose to use the _oc_get_ tool to retrieve pod information from the `openshift-lightspeed` namespace. You can view the tool's output by clicking the **oc_get** button displayed after the response. This information was used by the model to generate the final answer containing the list of all pods in that namespace.